// <auto-generated />
using System;
using GearShare.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearShare.Api.Migrations
{
    [DbContext(typeof(GearShareDbContext))]
    [Migration("20260729102808_SeedGearItems")]
    partial class SeedGearItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearShare.Api.Models.GearItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyRateCents")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("GearItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "Camping",
                            CreatedAt = new DateTime(2026, 6, 29, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(3709),
                            DailyRateCents = 2500,
                            Description = "Spacious tent for family trips.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "4-Person Camping Tent"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = "Water",
                            CreatedAt = new DateTime(2026, 7, 4, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5601),
                            DailyRateCents = 4500,
                            Description = "Lightweight kayak for calm water.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Kayak - Single"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-cccccccccccc"),
                            Category = "Climbing",
                            CreatedAt = new DateTime(2026, 7, 9, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5630),
                            DailyRateCents = 1500,
                            Description = "Beginner-friendly climbing harness.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Climbing Harness"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-0000-0000-0000-dddddddddddd"),
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 7, 11, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5637),
                            DailyRateCents = 800,
                            Description = "Adjustable poles for all skill levels.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Ski Poles - Pair"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0000-eeeeeeeeeeee"),
                            Category = "Cycling",
                            CreatedAt = new DateTime(2026, 7, 14, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5643),
                            DailyRateCents = 6000,
                            Description = "Full-suspension trail bike.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Mountain Bike"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-ffffffffffff"),
                            Category = "Water",
                            CreatedAt = new DateTime(2026, 7, 17, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5650),
                            DailyRateCents = 3000,
                            Description = "5mm wetsuit for cold water.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Wetsuit - Medium"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-a1a1a1a1a1a1"),
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 7, 19, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5656),
                            DailyRateCents = 5500,
                            Description = "All-mountain board, size 156.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Snowboard + Bindings"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-b2b2b2b2b2b2"),
                            Category = "Climbing",
                            CreatedAt = new DateTime(2026, 7, 24, 10, 28, 3, 234, DateTimeKind.Utc).AddTicks(5663),
                            DailyRateCents = 2000,
                            Description = "Dry-treated climbing rope.",
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Available",
                            Title = "Rope - 60m Dry"
                        });
                });

            modelBuilder.Entity("GearShare.Api.Models.RentalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GearItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RenterEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RenterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RenterPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.ToTable("RentalRequests");
                });

            modelBuilder.Entity("GearShare.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "$2a$11$qVoZScKJ/tbDjNdOeL3sIueh/iXK8L51siIESiFH//4Vb/8XIxobS",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$CrS8co4U7EA9ldadkveLZ.dFxhA9.Lk02c1uCdSXvisMTjZtV5uGm",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("GearShare.Api.Models.GearItem", b =>
                {
                    b.HasOne("GearShare.Api.Models.User", "Owner")
                        .WithMany("GearItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GearShare.Api.Models.RentalRequest", b =>
                {
                    b.HasOne("GearShare.Api.Models.GearItem", "GearItem")
                        .WithMany("RentalRequests")
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearItem");
                });

            modelBuilder.Entity("GearShare.Api.Models.GearItem", b =>
                {
                    b.Navigation("RentalRequests");
                });

            modelBuilder.Entity("GearShare.Api.Models.User", b =>
                {
                    b.Navigation("GearItems");
                });
#pragma warning restore 612, 618
        }
    }
}
